#
#   Start command: docker-compose up
#
version: "3"
services:
#   DataBase's
#      MongoDB
  mongodb:
    image: mongo:latest
    network_mode: microservices
    container_name: mongodb-ms
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: mongodb@2020
    restart: unless-stopped
#   API's
#      ProductCatalog
  productcatalog:
    image: openjdk:8
    network_mode: microservices
    container_name: ms-product-catalog
    expose:
      - 8081
    ports:
      - 8081:8081
    volumes:
          - /home/pramod/Desktop:/var/tmp
    restart: unless-stopped
volumes:
  postgres-data: