server:
  port: 9090
spring:
  cloud: 
   gateway: 
    routes:
      - id: ms-productcatalog-v1
        uri: 'http://localhost:8084'
        predicates:
          - Path=/product/**
          - Query=src,mobile
      - id: ms-productcatalog-v2
        uri: 'http://localhost:8081'
        predicates:
          - Path=/product/**